# Generated by Django 5.1.3 on 2024-12-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='behavior',
            field=models.CharField(choices=[('deposit', 'Депозит'), ('credit', 'Кредит')], default='credit', max_length=20, verbose_name='Поведение типа'),
        ),
    ]
