# Generated by Django 5.1.3 on 2024-12-14 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_producttype_behavior'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'permissions': [('approve_transaction', 'Может одобрять транзакции')], 'verbose_name': 'Транзакция', 'verbose_name_plural': 'Транзакции'},
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Разрешения'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(null=True, verbose_name='Одобрение'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Одобрено старшим менеджером'),
        ),
    ]
