# Generated by Django 5.1.3 on 2024-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_transaction_options_role_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approved',
            field=models.BooleanField(choices=[(None, 'Ожидает'), (True, 'Одобрена'), (False, 'Отклонена')], null=True, verbose_name='Одобрение'),
        ),
    ]
